all:
  hosts:
    k-master:
      ansible_host: 192.168.0.140
      ip: 192.168.0.140
      access_ip: 192.168.0.140
    k-node1:
      ansible_host: 192.168.0.141
      ip: 192.168.0.141
      access_ip: 192.168.0.141
    k-node2:
      ansible_host: 192.168.0.142
      ip: 192.168.0.142
      access_ip: 192.168.0.142
    k-node3:
      ansible_host: 192.168.0.143
      ip: 192.168.0.143
      access_ip: 192.168.0.143
  children:
    kube-master:
      hosts:
        k-master:
    kube-node:
      hosts:
        k-master:
        k-node1:
        k-node2:
        k-node3:
    etcd:
      hosts:
        k-master:
        k-node1:
        k-node2:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
